
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/XJCode250323489/AdSpec.git'
source 'https://gitee.com/jyadteam/JYSpecs.git'

target 'AdMulXSDK_Example' do
  use_frameworks!
  
  pod 'AdMulXSDK', :path => '../'
  
  pod 'SVProgressHUD'
  
  target 'AdMulXSDK_Tests' do
    inherit! :search_paths

    
  end
end
