
platform :ios, '11.0'

target 'AdMulXSDK_Example' do
  use_frameworks!
  
  pod 'AdMulXSDK', :path => '../'
  
  pod 'SVProgressHUD'
  
  target 'AdMulXSDK_Tests' do
    inherit! :search_paths

    
  end
end
