
platform :ios, '11.0'

target 'AdMulXSDK_Example' do
  use_frameworks!
  
  pod 'AdMulXSDK', :path => '../'
  pod 'GDTMobSDK', '4.15.80'
  pod 'KSAdSDK', '5.3.20.1'
  pod 'SigmobAd-iOS', '4.20.10'
  pod 'OctopusSDK', '2.6.4.20'
  pod 'MSMobAdSDKv3','3.0.9.1'
  pod 'AdGainSDK', '4.2.7.1'
  pod 'AdWangMaiSDK', '7.8.4.32'
  pod 'BaiduMobAdSDK', '10.050'
  
  pod 'SVProgressHUD'
  
  target 'AdMulXSDK_Tests' do
    inherit! :search_paths

    
  end
end
